// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: trade.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeServiceClient is the client API for TradeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeServiceClient interface {
	// 创建交易单
	CreateTrade(ctx context.Context, in *CreateTradeReq, opts ...grpc.CallOption) (*CreateTradeRes, error)
	// 广播交易单
	SubmitTrade(ctx context.Context, in *SubmitTradeReq, opts ...grpc.CallOption) (*SubmitTradeRes, error)
	// 创建汇总交易单
	CreateSummaryTx(ctx context.Context, in *CreateSummaryTxReq, opts ...grpc.CallOption) (*CreateSummaryTxRes, error)
}

type tradeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeServiceClient(cc grpc.ClientConnInterface) TradeServiceClient {
	return &tradeServiceClient{cc}
}

func (c *tradeServiceClient) CreateTrade(ctx context.Context, in *CreateTradeReq, opts ...grpc.CallOption) (*CreateTradeRes, error) {
	out := new(CreateTradeRes)
	err := c.cc.Invoke(ctx, "/service.TradeService/CreateTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) SubmitTrade(ctx context.Context, in *SubmitTradeReq, opts ...grpc.CallOption) (*SubmitTradeRes, error) {
	out := new(SubmitTradeRes)
	err := c.cc.Invoke(ctx, "/service.TradeService/SubmitTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) CreateSummaryTx(ctx context.Context, in *CreateSummaryTxReq, opts ...grpc.CallOption) (*CreateSummaryTxRes, error) {
	out := new(CreateSummaryTxRes)
	err := c.cc.Invoke(ctx, "/service.TradeService/CreateSummaryTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServiceServer is the server API for TradeService service.
// All implementations must embed UnimplementedTradeServiceServer
// for forward compatibility
type TradeServiceServer interface {
	// 创建交易单
	CreateTrade(context.Context, *CreateTradeReq) (*CreateTradeRes, error)
	// 广播交易单
	SubmitTrade(context.Context, *SubmitTradeReq) (*SubmitTradeRes, error)
	// 创建汇总交易单
	CreateSummaryTx(context.Context, *CreateSummaryTxReq) (*CreateSummaryTxRes, error)
	mustEmbedUnimplementedTradeServiceServer()
}

// UnimplementedTradeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTradeServiceServer struct {
}

func (UnimplementedTradeServiceServer) CreateTrade(context.Context, *CreateTradeReq) (*CreateTradeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedTradeServiceServer) SubmitTrade(context.Context, *SubmitTradeReq) (*SubmitTradeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTrade not implemented")
}
func (UnimplementedTradeServiceServer) CreateSummaryTx(context.Context, *CreateSummaryTxReq) (*CreateSummaryTxRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSummaryTx not implemented")
}
func (UnimplementedTradeServiceServer) mustEmbedUnimplementedTradeServiceServer() {}

// UnsafeTradeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServiceServer will
// result in compilation errors.
type UnsafeTradeServiceServer interface {
	mustEmbedUnimplementedTradeServiceServer()
}

func RegisterTradeServiceServer(s grpc.ServiceRegistrar, srv TradeServiceServer) {
	s.RegisterService(&TradeService_ServiceDesc, srv)
}

func _TradeService_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TradeService/CreateTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).CreateTrade(ctx, req.(*CreateTradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_SubmitTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).SubmitTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TradeService/SubmitTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).SubmitTrade(ctx, req.(*SubmitTradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_CreateSummaryTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSummaryTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).CreateSummaryTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TradeService/CreateSummaryTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).CreateSummaryTx(ctx, req.(*CreateSummaryTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeService_ServiceDesc is the grpc.ServiceDesc for TradeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.TradeService",
	HandlerType: (*TradeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrade",
			Handler:    _TradeService_CreateTrade_Handler,
		},
		{
			MethodName: "SubmitTrade",
			Handler:    _TradeService_SubmitTrade_Handler,
		},
		{
			MethodName: "CreateSummaryTx",
			Handler:    _TradeService_CreateSummaryTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade.proto",
}
