// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: wallet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	// 创建钱包
	CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletRes, error)
	// 通过WalletID查询钱包
	FindWalletByWalletID(ctx context.Context, in *FindWalletByWalletIDReq, opts ...grpc.CallOption) (*FindWalletByWalletIDRes, error)
	// 通过WalletID查询钱包
	FindWalletByParams(ctx context.Context, in *FindWalletByParamsReq, opts ...grpc.CallOption) (*FindWalletByParamsRes, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletRes, error) {
	out := new(CreateWalletRes)
	err := c.cc.Invoke(ctx, "/service.WalletService/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) FindWalletByWalletID(ctx context.Context, in *FindWalletByWalletIDReq, opts ...grpc.CallOption) (*FindWalletByWalletIDRes, error) {
	out := new(FindWalletByWalletIDRes)
	err := c.cc.Invoke(ctx, "/service.WalletService/FindWalletByWalletID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) FindWalletByParams(ctx context.Context, in *FindWalletByParamsReq, opts ...grpc.CallOption) (*FindWalletByParamsRes, error) {
	out := new(FindWalletByParamsRes)
	err := c.cc.Invoke(ctx, "/service.WalletService/FindWalletByParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility
type WalletServiceServer interface {
	// 创建钱包
	CreateWallet(context.Context, *CreateWalletReq) (*CreateWalletRes, error)
	// 通过WalletID查询钱包
	FindWalletByWalletID(context.Context, *FindWalletByWalletIDReq) (*FindWalletByWalletIDRes, error)
	// 通过WalletID查询钱包
	FindWalletByParams(context.Context, *FindWalletByParamsReq) (*FindWalletByParamsRes, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (UnimplementedWalletServiceServer) CreateWallet(context.Context, *CreateWalletReq) (*CreateWalletRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedWalletServiceServer) FindWalletByWalletID(context.Context, *FindWalletByWalletIDReq) (*FindWalletByWalletIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindWalletByWalletID not implemented")
}
func (UnimplementedWalletServiceServer) FindWalletByParams(context.Context, *FindWalletByParamsReq) (*FindWalletByParamsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindWalletByParams not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.WalletService/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateWallet(ctx, req.(*CreateWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_FindWalletByWalletID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWalletByWalletIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).FindWalletByWalletID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.WalletService/FindWalletByWalletID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).FindWalletByWalletID(ctx, req.(*FindWalletByWalletIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_FindWalletByParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWalletByParamsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).FindWalletByParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.WalletService/FindWalletByParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).FindWalletByParams(ctx, req.(*FindWalletByParamsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _WalletService_CreateWallet_Handler,
		},
		{
			MethodName: "FindWalletByWalletID",
			Handler:    _WalletService_FindWalletByWalletID_Handler,
		},
		{
			MethodName: "FindWalletByParams",
			Handler:    _WalletService_FindWalletByParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
